[package]
name = "vidyut"
description = "A lightning-fast Sanskrit parser"
homepage = "https://ambuda.org"
version = "0.1.0"
edition = "2021"
default-run = "vidyut"

[profile.release]
# Enable debug symbols so that we can profile release code.
debug = true

[dependencies]
clap = { version = "4.0.12", features = ["derive"] }
csv = "1.1.6"
env_logger = "0.9.1"
lazy_static = "1.4.0"
log = "0.4.17"
multimap = "0.8.3"
priority-queue = "1.2.3"
regex = "1.6.0"
serde = { version = "1.0.145", features = ["derive"] }
glob = "0.3.0"
fst = "0.4.7"
modular-bitfield = "0.11.2"
rand = "0.8.5"

[[bench]]
name = "lexicon"
harness = false

[dev-dependencies]
bencher = "0.1.5"
