[workspace]

members = [
    "vidyut-kosha",
]

[package]
name = "vidyut"
version = "0.1.0"
authors = ["Arun Prasad <ambuda.library@gmail.com>"]
description = "A Sanskrit toolkit"
homepage = "https://github.com/ambuda-org/vidyut"
repository = "https://github.com/ambuda-org/vidyut"
categories = ["text-processing"]
keywords = ["sanskrit"]
license = "MIT"
edition = "2021"

[profile.release]
# Enable debug symbols so that we can profile release code.
debug = true

[dependencies]
vidyut-kosha = { path = "vidyut-kosha" }
clap = { version = "4.0.12", features = ["derive"] }
csv = "1.1.6"
env_logger = "0.9.1"
lazy_static = "1.4.0"
log = "0.4.17"
multimap = "0.8.3"
priority-queue = "1.2.3"
regex = "1.6.0"
glob = "0.3.0"
fst = "0.4.7"
modular-bitfield = "0.11.2"
rand = "0.8.5"

[dev-dependencies]
bencher = "0.1.5"
tempfile = "3.3.0"
