[package]
name = "sanskrit-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
csv = "1.1.6"
env_logger = "0.9.1"
log = "0.4.17"
multimap = "0.8.3"
priority-queue = "1.2.3"
regex = "1.6.0"
serde = { version = "1.0.145", features = ["derive"] }
